workflows:
  ios-workflow:
    name: Game by Samir iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    scripts:
      - name: Initialize Project
        script: | 
          flutter create .
      - name: Get Packages
        script: | 
          flutter pub get
      - name: Generate App Icons
        script: | 
          flutter pub run flutter_launcher_icons
      - name: Build IPA
        script: | 
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
